# This is a basic workflow to help you get started with Actions

name: Denodo Solution Manager CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push  request event but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # CI CD Steps
      - name: Executing Denodo Solution Manager CI CD Pipeline
        run: ec2-user/home/solution-manager/bin/import.sh -f ec2-user/home/solution-manager/bin/pull.vql -h ec2-54-90-23-215.compute-1.amazonaws.com:9999/test_main?sesa447330@admin

